language: python
sudo: required
services:
  - docker
notifications:
  email: false
python:
  - "3.6"
before_install:
  - docker build -t brochat-bot .
script:
  - python3 objs/duel_item.py
  - python3 main.py
